version: 1.0.0
name: example-workflow
namespace: automl
stages: 
  train: 
    - step_name: "model_1"
      path_to_executable: models/model_1.py
      dependency_path: models/requirements.txt
      cpu_request: 0.2
      memory_request: 200
      timeout: 30
    - step_name: "model_2"
      path_to_executable: models/model_2.py
      dependency_path: models/requirements.txt
      cpu_request: 0.2
      memory_request: 200
      timeout: 30
    - step_name: "model_3"
      path_to_executable: models/model_3.py
      dependency_path: models/requirements.txt
      cpu_request: 0.2
      memory_request: 200
      timeout: 30
  compare: 
    - step_name: "best_model"
      path_to_executable: compare.py
      dependency_path: models/requirements.txt
      cpu_request: 0.2
      memory_request: 200
      timeout: 30
  serve:
    - step_name: "serve_model_1"
      path_to_executable: deploy/serve_1.py
      dependency_path: deploy/requirements.txt
      command: ["gunicorn", "-b", "0.0.0.0:5000", "deploy.serve:app"]
      timeout: 20
      cpu_request: 0.2
      memory_request: 200
      service:
        max_startup_time_seconds: 10
        port: 5000
        ingress: True
    - step_name: "serve_model_2"
      path_to_executable: deploy/serve_2.py
      dependency_path: deploy/requirements.txt
      command: ["gunicorn", "-b", "0.0.0.0:3000", "deploy.serve_2:app"]
      timeout: 20
      cpu_request: 0.2
      memory_request: 200
      service:
        max_startup_time_seconds: 10
        port: 3000
        ingress: False
        
